import { MessageVersionWithEditor } from '@/services/message-version.service';
import { Badge } from '@/components/ui/badge';
import { formatDistanceToNow } from 'date-fns';
import { Bot, User } from 'lucide-react';

interface MessageVersionHistoryProps {
  versions: MessageVersionWithEditor[];
  currentContent: string;
}

export function MessageVersionHistory({
  versions,
  currentContent,
}: MessageVersionHistoryProps) {
  if (versions.length === 0) {
    return (
      <p className="text-sm text-muted-foreground py-4 text-center">
        No version history recorded yet.
      </p>
    );
  }

  return (
    <div className="space-y-3" role="list" aria-label="Message version history">
      {versions.map((version, index) => {
        const isLatest = index === 0;
        const matchesCurrent = version.content === currentContent;
        const editorName =
          (version.editor as { full_name?: string | null } | null)?.full_name ?? 'Unknown editor';
        const isAiGenerated = !version.edited_by;

        return (
          <div
            key={version.id}
            role="listitem"
            className={`rounded-lg border p-3 transition-colors ${
              isLatest ? 'border-primary/40 bg-primary/5' : 'border-border bg-background'
            }`}
          >
            <div className="flex items-center gap-2 flex-wrap mb-2">
              <span
                className="text-xs font-semibold text-muted-foreground"
                aria-label={`Version ${version.version_number}`}
              >
                v{version.version_number}
              </span>

              {isLatest && (
                <Badge variant="default" className="text-xs h-5">
                  Current
                </Badge>
              )}
              {matchesCurrent && !isLatest && (
                <Badge variant="outline" className="text-xs h-5">
                  Matches active
                </Badge>
              )}

              {isAiGenerated ? (
                <Badge variant="secondary" className="text-xs h-5 flex items-center gap-1">
                  <Bot className="h-3 w-3" aria-hidden="true" /> AI Generated
                </Badge>
              ) : (
                <Badge variant="outline" className="text-xs h-5 flex items-center gap-1">
                  <User className="h-3 w-3" aria-hidden="true" /> Human Edit
                </Badge>
              )}

              <span className="ml-auto text-xs text-muted-foreground">
                <time dateTime={version.created_at}>
                  {formatDistanceToNow(new Date(version.created_at), {
                    addSuffix: true,
                  })}
                </time>
              </span>
            </div>

            <div className="text-xs text-muted-foreground mb-2">
              {isAiGenerated ? (
                <span>Generated by AI</span>
              ) : (
                <span>Edited by {editorName}</span>
              )}
              {version.change_reason && (
                <span className="ml-2 text-muted-foreground/70">
                  — {version.change_reason}
                </span>
              )}
            </div>

            {/* Content preview — plain text, no HTML */}
            <p className="text-xs text-foreground/80 whitespace-pre-wrap break-words line-clamp-3 font-mono">
              {version.content.slice(0, 300)}
              {version.content.length > 300 ? '…' : ''}
            </p>
          </div>
        );
      })}
    </div>
  );
}
